language: ruby

rvm:
  - 2.5

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer


cache: bundler # speeds up the build

before_install:
- chmod +x ./cibuild
- openssl aes-256-cbc -K $encrypted_5997fd602279_key -iv $encrypted_5997fd602279_iv
  -in mygithub.enc -out mygithub -d
- chmod 600 github_deploy_key
- eval $(ssh-agent -s)
- ssh-add github_deploy_key

branches:
  only:
  - release

script: ./cibuild

deploy:
  provider: pages
  local-dir: "./site"
  target-branch: master
  skip-cleanup: true
  keep-history: true
  on:
    branch: release
